# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TVShows' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TVShows
  pod 'Alamofire'
  pod 'SVProgressHUD'
  pod 'CodableAlamofire'
  pod "PromiseKit/CorePromise", "~> 6.0"
  pod 'PromiseKit/Alamofire'
  pod 'Kingfisher', '~> 5.0'
  pod 'Keychain', '~> 0.3'
  target 'TVShowsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
